name: GetMoarFediverse

on:
  # uncomment the following 2 lines so that it runs automatically every 15 minutes
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  moar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: g3rv4/GetMoarFediverse@main
        with:
          config_file: https://gist.githubusercontent.com/felixwttr/a4be146b86ccea4566adf2d7810af0d3/raw/85a06def2a7425dd23deade81f4b3004ebcb7d5a/config.json # ${{ github.workspace }}/config.json
          api_key: ${{ secrets.FAKERELAY_APIKEY }}
      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v1
