name: GetMoarFediverse

on:
  # uncomment the following 2 lines so that it runs automatically every 15 minutes
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  moar:
    runs-on: ubuntu-latest
    steps:
      - name: Get Gist
        id: config
        # You may pin to the exact commit or the version.
        # uses: andymckay/get-gist-action@834695896192ac70c1e095ada6320cd66d6b90a6
        uses: andymckay/get-gist-action@0.1
        with:
          # URL to the gist
          gistURL: https://gist.github.com/felixwttr/a4be146b86ccea4566adf2d7810af0d3
      - uses: actions/checkout@v3
      - uses: g3rv4/GetMoarFediverse@main
        with:
          config_file: ${{ steps.config.outputs.file }} # ${{ github.workspace }}/config.json
          api_key: ${{ secrets.FAKERELAY_APIKEY }}
      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v1
